@startuml
skinparam actorStyle Hollow
left to right direction
skinparam Linetype polyline
!include ./themes/dark.puml

user <|-- staff
user <|-- manager
user <|-- technician

rectangle "Hospital Incident Manager"{
(UC1 - login).down.>(UC2 - authenticate):include
(UC6 - create ticket)
(UC8 - visualize global tickets)
(UC14 - visualize department tickets)
(UC11 - filter tickets).up.>(UC8 - visualize global tickets):extends
(UC11 - filter tickets).up.>(UC14 - visualize department tickets):extends
(UC10 - download ticket list).up.>(UC8 - visualize global tickets):extends
(UC10 - download ticket list).up.>(UC14 - visualize department tickets):extends
(UC12 - comment on ticket).up.>(UC8 - visualize global tickets):extends
(UC12 - comment on ticket).up.>(UC14 - visualize department tickets):extends
(UC7 - visualize my incidents)
(UC9 - assign department to ticket).up.>(UC8 - visualize global tickets):extends
(UC5 - mark notification as read).up.>(UC4 - open notification tray):extends
(UC3 - receive notification) .up.> (UC4 - open notification tray) : include
(UC13 - view audit log)
(UC15 - update ticket status).up.>(UC14 - visualize department tickets):extends
(UC16 - assign technician to ticket).up.>(UC14 - visualize department tickets):extends
(UC17 - close ticket).up.>(UC8 - visualize global tickets): extends
}

user --> (UC1 - login)
user --> (UC4 - open notification tray)

staff --> (UC6 - create ticket)
staff --> (UC7 - visualize my incidents)

manager --> (UC8 - visualize global tickets)
manager --> (UC13 - view audit log)

technician --> (UC14 - visualize department tickets)

(UC2 - authenticate) --> "authentication authority"

@enduml